// GENERATED by scripts/build-florida-geometry.mts — do not edit by hand.
// Sources: U.S. Census Bureau cartographic boundaries (cb_2024_us_state_500k) and
// Natural Earth 1:10m Admin-0 countries. Both public domain. See docs/asset-sources.md.

import type { ViewTransform } from "@/lib/geo";

export const mapProjection = {
  width: 1000,
  height: 815.4,
  frame: {"west":-88.6,"east":-76.4,"south":22.6,"north":31.6},
  transform: {"scale":5080.222301163643,"tx":377.1434179267001,"ty":691.3825747401767} satisfies ViewTransform,
} as const;
