/**
 * Builds content/florida/regions-geometry.ts: the six "Florida today" regions,
 * made by grouping Florida's 67 counties and dissolving them into one shape each.
 *
 * Usage:
 *   node scripts/build-florida-regions.mts <cb_2024_us_county_500k.zip>
 *
 * Source: U.S. Census Bureau cartographic boundary files (public domain).
 * Run after build-florida-geometry.mts (uses its projection).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import mapshaper from "mapshaper";
import { makeProjector, type LonLat } from "../lib/geo.ts";
import { mapProjection } from "../content/florida/projection.ts";

const [countyZip] = process.argv.slice(2);
if (!countyZip) {
  console.error("Usage: node scripts/build-florida-regions.mts <county.zip>");
  process.exit(1);
}

/** Region ids match content/florida/ecosystem.ts. Every Florida county appears exactly once. */
const REGION_COUNTIES: Record<string, string[]> = {
  northwest: [
    "Escambia", "Santa Rosa", "Okaloosa", "Walton", "Holmes", "Washington", "Bay", "Jackson", "Calhoun",
    "Gulf", "Liberty", "Franklin", "Gadsden", "Leon", "Wakulla", "Jefferson", "Madison", "Taylor",
  ],
  "north-central": [
    "Hamilton", "Suwannee", "Lafayette", "Dixie", "Columbia", "Gilchrist", "Levy", "Alachua", "Union",
    "Bradford", "Marion", "Clay",
  ],
  northeast: ["Nassau", "Duval", "Baker", "St. Johns", "Putnam", "Flagler"],
  central: [
    "Volusia", "Seminole", "Orange", "Osceola", "Lake", "Sumter", "Brevard", "Indian River", "Polk",
    "Okeechobee", "St. Lucie",
  ],
  "tampa-bay": [
    "Citrus", "Hernando", "Pasco", "Pinellas", "Hillsborough", "Manatee", "Sarasota", "Hardee", "DeSoto",
    "Highlands", "Charlotte",
  ],
  south: ["Lee", "Collier", "Glades", "Hendry", "Martin", "Palm Beach", "Broward", "Miami-Dade", "Monroe"],
};

const lookup = Object.fromEntries(
  Object.entries(REGION_COUNTIES).flatMap(([region, counties]) => counties.map((c) => [c, region])),
);
const assigned = Object.values(REGION_COUNTIES).flat();
if (assigned.length !== 67 || new Set(assigned).size !== 67) {
  throw new Error(`Expected 67 unique counties, got ${assigned.length} (${new Set(assigned).size} unique)`);
}

const each = `region = ${JSON.stringify(lookup)}[NAME]`;
const base =
  `-i "${countyZip}" -filter 'STATEFP=="12"' -each '${each}' ` +
  `-filter 'region != null' -dissolve region -simplify interval=500 keep-shapes -filter-islands min-area=1.5km2`;

const run = async (cmd: string) =>
  JSON.parse(Object.values(await mapshaper.applyCommands(`${cmd} -o out.json format=geojson`))[0].toString());

const shapes = await run(base);
const points = await run(`${base} -points inner`);

const project = makeProjector(mapProjection.transform);
const r = (v: number) => Math.round(v * 10) / 10;
const ring = (coords: LonLat[]) =>
  "M" + coords.map((p) => project(p).map(r).join(" ")).join("L") + "Z";

type Geom = { type: "Polygon"; coordinates: LonLat[][] } | { type: "MultiPolygon"; coordinates: LonLat[][][] };
const out: Record<string, { d: string; label: [number, number] }> = {};
for (const f of shapes.features as { properties: { region: string }; geometry: Geom }[]) {
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  out[f.properties.region] = { d: polys.flatMap((poly) => poly.map(ring)).join(""), label: [0, 0] };
}
for (const f of points.features as { properties: { region: string }; geometry: { coordinates: LonLat } }[]) {
  const [x, y] = project(f.geometry.coordinates);
  out[f.properties.region].label = [r(x), r(y)];
}

// Bounding box of all regions (map units), padded — used to zoom the explorer map to Florida.
let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
for (const { d } of Object.values(out)) {
  for (const m of d.matchAll(/(-?[\d.]+) (-?[\d.]+)/g)) {
    const x = +m[1], y = +m[2];
    minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y);
  }
}
const PAD = 18;
const bounds = { x: r(minX - PAD), y: r(minY - PAD), width: r(maxX - minX + PAD * 2), height: r(maxY - minY + PAD * 2) };

const file = `// GENERATED by scripts/build-florida-regions.mts — do not edit by hand.
// Source: U.S. Census Bureau cartographic boundary files (counties), public domain.
// Regions are groups of whole counties; see the script for the assignments.

/** Region outlines (SVG path, map units) and an interior label point. */
export const regionShapes: Record<string, { d: string; label: readonly [number, number] }> = ${JSON.stringify(out)};

/** Padded bounding box of Florida in map units. */
export const floridaBounds = ${JSON.stringify(bounds)} as const;
`;
const target = fileURLToPath(new URL("../content/florida/regions-geometry.ts", import.meta.url));
writeFileSync(target, file);
console.log(`Wrote ${target} (${file.length} chars): ${Object.keys(out).join(", ")}`);
